class MyExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel
{

  override bool CanCollideWith(Actor other, bool passive){
    Super.CanCollideWith(other, passive);
    if(other is "BioProjAlt"){
      A_Die();
      other.Destroy();
    }
    return true;
  }
}

/*class MyBackPack : BackPack replaces BackPack
{

  override void AttachToOwner(Actor owner){
    Super.AttachToOwner(owner);

    let g = Globals(EventHandler.Find("Globals"));

    for(int i = 0; i < g.allCompanions.size(); i++){
      int amt = owner.countinv(g.allCompanions[i].."Ammo");
      if(amt > 0){
        owner.GiveInventory(g.allCompanions[i].."Gun", 1);
      }
    }
  }

  override bool ShouldRespawn(){
    return false;
  }
}*/