class CompanionZombieManGun : BaseDeployer
{
  Default
  {
    Tag "Zombie Man";
    Weapon.AmmoType2 "CompanionZombieManAmmo";
    Inventory.PickupMessage "Got Zombie Man!";
    BaseDeployer.price 1;
    Weapon.SlotPriority 1;
  }
  States
  {
    Spawn:
      POSS A -1;
      Stop;
  }
}

Class MarineCompanionPistolGun : BaseDeployer
{
  Default
  {
    Tag "Pistol Marine";
    Weapon.AmmoType2 "MarineCompanionPistolAmmo";
    Inventory.PickupMessage "Got Pistol Marine!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      ALY2 A -1;
      Stop;
  }
}

Class MarineCompanionFistGun : BaseDeployer
{
  Default
  {
    Tag "Berserk Marine";
    Weapon.AmmoType2 "MarineCompanionFistAmmo";
    Inventory.PickupMessage "Got Berserk Marine!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      ALY1 A -1;
      Stop;
  }
}

Class MarineCompanionSGGun : BaseDeployer
{
  Default
  {
    Tag "Shotgun Marine";
    Weapon.AmmoType2 "MarineCompanionSGAmmo";
    Inventory.PickupMessage "Got Shotgun Marine!";
    BaseDeployer.price 60;
    Weapon.SlotPriority 60;
  }
  States
  {
    Spawn:
      ALY5 A -1;
      Stop;
  }
}

Class MarineCompanionSSGGun : BaseDeployer
{
  Default
  {
    Tag "Super Shotgun Marine";
    Weapon.AmmoType2 "MarineCompanionSSGAmmo";
    Inventory.PickupMessage "Got Super Shotgun Marine!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      AL11 A -1;
      Stop;
  }
}

Class MarineCompanionCGGun : BaseDeployer
{
  Default
  {
    Tag "Chaingun Marine";
    Weapon.AmmoType2 "MarineCompanionCGAmmo";
    Inventory.PickupMessage "Got Chaingun Marine!";
    BaseDeployer.price 125;
    Weapon.SlotPriority 125;
  }
  States
  {
    Spawn:
      ALY4 A -1;
      Stop;
  }
}

Class MarineCompanionRocketGun : BaseDeployer
{
  Default
  {
    Tag "Rocket Launcher Marine";
    Weapon.AmmoType2 "MarineCompanionRocketAmmo";
    Inventory.PickupMessage "Got Rocket Launcher Marine!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      ALY9 A -1;
      Stop;
  }
}

Class MarineCompanionPlasmaGun : BaseDeployer
{
  Default
  {
    Tag "Plasma Rifle Marine";
    Weapon.AmmoType2 "MarineCompanionPlasmaAmmo";
    Inventory.PickupMessage "Got Plasma Rifle Marine!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      ALY8 A -1;
      Stop;
  }
}

Class MarineCompanionBFG9000Gun : BaseDeployer
{
  Default
  {
    Tag "BFG9000 Marine";
    Weapon.AmmoType2 "MarineCompanionBFG9000Ammo";
    Inventory.PickupMessage "Got BFG9000 Marine!";
    BaseDeployer.price 400;
    Weapon.SlotPriority 400;
  }
  States
  {
    Spawn:
      AL10 A -1;
      Stop;
  }
}

Class MarineCompanionBFG10KGun : BaseDeployer
{
  Default
  {
    Tag "BFG10K Marine";
    Weapon.AmmoType2 "MarineCompanionBFG10KAmmo";
    Inventory.PickupMessage "Got BFG10K Marine!";
    BaseDeployer.price 400;
    Weapon.SlotPriority 400;
  }
  States
  {
    Spawn:
      AL15 A -1;
      Stop;
  }
}

Class MarineCompanionGLGun : BaseDeployer
{
  Default
  {
    Tag "Grenade Launcher Marine";
    Weapon.AmmoType2 "MarineCompanionGLAmmo";
    Inventory.PickupMessage "Got Grenade Launcher Marine!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      AL14 A -1;
      Stop;
  }
}

Class MarineCompanionHSMissileGun : BaseDeployer
{
  Default
  {
    Tag "Heat Seeking Missile Marine";
    Weapon.AmmoType2 "MarineCompanionHSMissileAmmo";
    Inventory.PickupMessage "Got Heat Seeking Missile Marine!";
    BaseDeployer.price 250;
    Weapon.SlotPriority 250;
  }
  States
  {
    Spawn:
      AL13 A -1;
      Stop;
  }
}

Class MarineCompanionRailgunGun : BaseDeployer
{
  Default
  {
    Tag "Railgun Marine";
    Weapon.AmmoType2 "MarineCompanionRailgunAmmo";
    Inventory.PickupMessage "Got Railgun Marine!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      AL12 A -1;
      Stop;
  }
}

Class MarineCompanionSniperGun : BaseDeployer
{
  Default
  {
    Tag "Sniper Marine";
    Weapon.AmmoType2 "MarineCompanionSniperAmmo";
    Inventory.PickupMessage "Got Sniper Marine!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      AL17 A -1;
      Stop;
  }
}

Class MarineCompanionFlameThrowerGun : BaseDeployer
{
  Default
  {
    Tag "Flame Thrower Marine";
    Weapon.AmmoType2 "MarineCompanionFlameThrowerAmmo";
    Inventory.PickupMessage "Got Flame Thrower Marine!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      AL16 A -1;
      Stop;
  }
}

Class MarineCompanionMGGun : BaseDeployer
{
  Default
  {
    Tag "Machine Gun Marine";
    Weapon.AmmoType2 "MarineCompanionMGAmmo";
    Inventory.PickupMessage "Got Machine Gun Marine!";
    BaseDeployer.price 75;
    Weapon.SlotPriority 75;
  }
  States
  {
    Spawn:
      ALY3 A -1;
      Stop;
  }
}

Class MarineCompanionMinigunGun : BaseDeployer
{
  Default
  {
    Tag "Minigun Marine";
    Weapon.AmmoType2 "MarineCompanionMinigunAmmo";
    Inventory.PickupMessage "Got Minigun Marine!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      ALY6 A -1;
      Stop;
  }
}

Class MarineCompanionChainsawGun : BaseDeployer
{
  Default
  {
    Tag "Chainsaw Marine";
    Weapon.AmmoType2 "MarineCompanionChainsawAmmo";
    Inventory.PickupMessage "Got Chainsaw Marine!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      ALY7 A -1;
      Stop;
  }
}

class CompanionShotgunGuyGun : BaseDeployer
{
  Default
  {
    Tag "Shotgun Guy";
    Weapon.AmmoType2 "CompanionShotgunGuyAmmo";
    Inventory.PickupMessage "Got Shotgun Guy!";
    BaseDeployer.price 5;
    Weapon.SlotPriority 5;
  }
  States
  {
    Spawn:
      SPOS A -1;
      Stop;
  }
}

class CompanionChaingunGuyGun : BaseDeployer
{
  Default
  {
    Tag "Chaingun Guy";
    Weapon.AmmoType2 "CompanionChaingunGuyAmmo";
    Inventory.PickupMessage "Got Chaingun Guy!";
    BaseDeployer.price 15;
    Weapon.SlotPriority 15;
  }
  States
  {
    Spawn:
      CPOS A -1;
      Stop;
  }
}

class CompanionDemonGun : BaseDeployer
{
  Default
  {
    Tag "Demon";
    Weapon.AmmoType2 "CompanionDemonAmmo";
    Inventory.PickupMessage "Got Demon!";
    BaseDeployer.price 6;
    Weapon.SlotPriority 6;
  }
  States
  {
    Spawn:
      SARG A -1;
      Stop;
  }
}

class CompanionSpectreGun : CompanionDemonGun
{
  Default
  {
    Tag "Spectre";
    Weapon.AmmoType2 "CompanionSpectreAmmo";
    Inventory.PickupMessage "Got Spectre!";
    RenderStyle "Translucent";
  }
}

class CompanionLostSoulGun : BaseDeployer
{
  Default
  {
    Tag "Lost Soul";
    Weapon.AmmoType2 "CompanionLostSoulAmmo";
    Inventory.PickupMessage "Got Lost Soul!";
    BaseDeployer.price 3;
    Weapon.SlotPriority 3;
  }
  States
  {
    Spawn:
      SKUL A -1;
      Stop;
  }
}

class CompanionCacodemonGun : BaseDeployer
{
  Default
  {
    Tag "Cacodemon";
    Weapon.AmmoType2 "CompanionCacodemonAmmo";
    Inventory.PickupMessage "Got Cacodemon!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      HEAD A -1;
      Stop;
  }
}

class CompanionPainElementalGun : BaseDeployer
{
  Default
  {
    Tag "Pain Elemental";
    Weapon.AmmoType2 "CompanionPainElementalAmmo";
    Inventory.PickupMessage "Got Pain Elemental!";
    BaseDeployer.price 300;
    Weapon.SlotPriority 300;
  }
  States
  {
    Spawn:
      PAIN A -1;
      Stop;
  }
}

class CompanionBaronOfHellGun : BaseDeployer
{
  Default
  {
    Tag "Baron of Hell";
    Weapon.AmmoType2 "CompanionBaronOfHellAmmo";
    Inventory.PickupMessage "Got Baron of Hell!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      BOSS A -1;
      Stop;
  }
}

class CompanionHellKnightGun : CompanionBaronOfHellGun
{
  Default
  {
    Tag "Hell Knight";
    Weapon.AmmoType2 "CompanionHellKnightAmmo";
    Inventory.PickupMessage "Got Hell Knight!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      BOS2 A -1;
      Stop;
  }
}

class CompanionArachnotronGun : BaseDeployer
{
  Default
  {
    Tag "Arachnotron";
    Weapon.AmmoType2 "CompanionArachnotronAmmo";
    Inventory.PickupMessage "Got Arachnotron!";
    BaseDeployer.price 75;
    Weapon.SlotPriority 75;
  }
  States
  {
    Spawn:
      BSPI A -1;
      Stop;
  }
}

class CompanionArchvileGun : BaseDeployer
{
  Default
  {
    Tag "Archvile";
    Weapon.AmmoType2 "CompanionArchvileAmmo";
    Inventory.PickupMessage "Got Archvile!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      VILE A -1;
      Stop;
  }
}

class CompanionFatsoGun : BaseDeployer
{
  Default
  {
    Tag "Mancubus";
    Weapon.AmmoType2 "CompanionFatsoAmmo";
    Inventory.PickupMessage "Got Mancubus!";
    BaseDeployer.price 75;
    Weapon.SlotPriority 75;
  }
  States
  {
    Spawn:
      FATT A -1;
      Stop;
  }
}

class CompanionCyberdemonGun : BaseDeployer
{
  Default
  {
    Tag "Cyberdemon";
    Weapon.AmmoType2 "CompanionCyberdemonAmmo";
    Inventory.PickupMessage "Got Cyberdemon!";
    BaseDeployer.price 500;
    Weapon.SlotPriority 500;
    Scale 0.2;
  }
  States
  {
    Spawn:
      CYBR A -1;
      Stop;
  }
}

class CompanionSpiderMastermindGun : BaseDeployer
{
  Default
  {
    Tag "Spider Mastermind";
    Weapon.AmmoType2 "CompanionSpiderMastermindAmmo";
    Inventory.PickupMessage "Got Spider Mastermind!";
    BaseDeployer.price 450;
    Weapon.SlotPriority 450;
    Scale 0.15;
  }
  States
  {
    Spawn:
      SPID A -1;
      Stop;
  }
}

class CompanionWolfensteinSSGun : BaseDeployer
{
  Default
  {
    Tag "Wolfenstein SS";
    Weapon.AmmoType2 "CompanionWolfensteinSSAmmo";
    Inventory.PickupMessage "Got Wolfenstein SS!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      SSWV A -1;
      Stop;
  }
}

class CompanionRevenantGun : BaseDeployer
{
  Default
  {
    Tag "Revenant";
    Weapon.AmmoType2 "CompanionRevenantAmmo";
    Inventory.PickupMessage "Got Revenant!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      SKEL A -1;
      Stop;
  }
}

class CompanionDoomImpGun : BaseDeployer
{
  Default
  {
    Tag "Imp";
    Weapon.AmmoType2 "CompanionDoomImpAmmo";
    Inventory.PickupMessage "Got Imp!";
    BaseDeployer.price 7;
    Weapon.SlotPriority 7;
  }
  States
  {
    Spawn:
      TROO A -1;
      Stop;
  }
}

Class BelphegorGun : BaseDeployer
{
  Default
  {
    Tag "Belphagor";
    Weapon.AmmoType2 "BelphegorAmmo";
    Inventory.PickupMessage "Got Belphegor!";
    BaseDeployer.price 250;
    Weapon.SlotPriority 250;
  }
  States
  {
    Spawn:
      BOS3 A -1;
      Stop;
  }
}

Class AfritGun : BaseDeployer
{
  Default
  {
    Tag "Afrit";
    Weapon.AmmoType2 "AfritAmmo";
    Inventory.PickupMessage "Got Afrit!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
    Inventory.Icon "FRITV0";
  }
  States
  {
    Spawn:
      FRIT V -1;
      Stop;
  }
}

Class MarauderGun : BaseDeployer
{
  Default
  {
    Tag "Marauder";
    Weapon.AmmoType2 "MarauderAmmo";
    Inventory.PickupMessage "Got Marauder!";
    BaseDeployer.price 75;
    Weapon.SlotPriority 75;
  }
  States
  {
    Spawn:
      MAUD A -1;
      Stop;
  }
}

Class ArachnophyteGun : BaseDeployer
{
  Default
  {
    Tag "Arachnophyte";
    Weapon.AmmoType2 "ArachnophyteAmmo";
    Inventory.PickupMessage "Got Arachnophyte!";
    BaseDeployer.price 450;
    Weapon.SlotPriority 450;
    Scale 0.2;
  }
  States
  {
    Spawn:
      APYT A -1;
      Stop;
  }
}

Class ArchonOfHellGun : BaseDeployer
{
  Default
  {
    Tag "Archon of Hell";
    Weapon.AmmoType2 "ArchonOfHellAmmo";
    Inventory.PickupMessage "Got Archon of Hell!";
    BaseDeployer.price 300;
    Weapon.SlotPriority 300;
  }
  States
  {
    Spawn:
      BOS4 A -1;
      Stop;
  }
}

Class MurderBallGun : BaseDeployer
{
  Default
  {
    Tag "Murder Ball";
    Weapon.AmmoType2 "MurderBallAmmo";
    Inventory.PickupMessage "Got Murder Ball!";
    BaseDeployer.price 999;
    Weapon.SlotPriority 999;
  }
  States
  {
    Spawn:
      BERS A -1;
      Stop;
  }
}

class ArachnobaronGun : BaseDeployer
{
  Default
  {
    Tag "Arachnobaron";
    Weapon.AmmoType2 "ArachnobaronAmmo";
    Inventory.PickupMessage "Got Arachnobaron!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      ARBR A -1;
      Stop;
  }
}

class BabyCacoGun : BaseDeployer
{
  Default
  {
    Tag "Baby Caco";
    Weapon.AmmoType2 "BabyCacoAmmo";
    Inventory.PickupMessage "Got Baby Caco!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      CACB A -1;
      Stop;
  }
}

class BeheadedKamikazeGun : BaseDeployer
{
  Default
  {
    Tag "Beheaded Kamikaze";
    Weapon.AmmoType2 "BeheadedKamikazeAmmo";
    Inventory.PickupMessage "Got Beheaded Kamikaze!";
    BaseDeployer.price 2;
    Weapon.SlotPriority 2;
  }
  States
  {
    Spawn:
      BKAM A -1;
      Stop;
  }
}

class AbaddonGun : BaseDeployer
{
  Default
  {
    Tag "Abaddon";
    Weapon.AmmoType2 "AbaddonAmmo";
    Inventory.PickupMessage "Got Abaddon!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      HED3 A -1;
      Stop;
  }
}

class AgathodemonGun : BaseDeployer
{
  Default
  {
    Tag "Agathodemon";
    Weapon.AmmoType2 "AgathodemonAmmo";
    Inventory.PickupMessage "Got Agathodemon!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      AGAH A -1;
      Stop;
  }
}

class AnotherAgathodemonGun : AgathodemonGun
{
  Default
  {
    Tag "Agathodemon Variant";
    Weapon.AmmoType2 "AnotherAgathodemonAmmo";
    Inventory.PickupMessage "Got Agathodemon variant!";
  }
}

class AgauresGun : BaseDeployer
{
  Default
  {
    Tag "Agaures";
    Weapon.AmmoType2 "AgauresAmmo";
    Inventory.PickupMessage "Got Agaures!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      AGUR A -1;
      Stop;
  }
}

class GhostlyAgauresGun : AgauresGun
{
  Default
  {
    Tag "Ghostly Agaures";
    Weapon.AmmoType2 "GhostlyAgauresAmmo";
    Inventory.PickupMessage "Got Ghostly Agaures!";
    RenderStyle "Translucent";
  }
}

class AnnihilatorGun : BaseDeployer
{
  Default
  {
    Tag "Annihilator";
    Weapon.AmmoType2 "AnnihilatorAmmo";
    Inventory.PickupMessage "Got Annihilator!";
    BaseDeployer.price 750;
    Weapon.SlotPriority 750;
    Scale 0.2;
  }
  States
  {
    Spawn:
      ANNI A -1;
      Stop;
  }
}

class AracnorbGun : BaseDeployer
{
  Default
  {
    Tag "Aracnorb";
    Weapon.AmmoType2 "AracnorbAmmo";
    Inventory.PickupMessage "Got Aracnorb!";
    BaseDeployer.price 30;
    Weapon.SlotPriority 30;
  }
  States
  {
    Spawn:
      ACNB A -1;
      Stop;
  }
}

class AracnorbQueenGun : BaseDeployer
{
  Default
  {
    Tag "Aracnorb Queen";
    Weapon.AmmoType2 "AracnorbQueenAmmo";
    Inventory.PickupMessage "Got Aracnorb Queen!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
    Scale 0.2;
  }
  States
  {
    Spawn:
      ARNQ A -1;
      Stop;
  }
}

class AugmentedArachnotronGun : BaseDeployer
{
  Default
  {
    Tag "Augmented Arachnotron";
    Weapon.AmmoType2 "AugmentedArachnotronAmmo";
    Inventory.PickupMessage "Got Augmented Arachnotron!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      BSP2 A -1;
      Stop;
  }
}

class AutoShotgunGuyGun : BaseDeployer
{
  Default
  {
    Tag "Auto Shotgun Guy";
    Weapon.AmmoType2 "AutoShotgunGuyAmmo";
    Inventory.PickupMessage "Got Auto Shotgun Guy!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      ASGZ A -1;
      Stop;
  }
}

class AzazelGun : BaseDeployer
{
  Default
  {
    Tag "Azazel";
    Weapon.AmmoType2 "AzazelAmmo";
    Inventory.PickupMessage "Got Azazel!";
    BaseDeployer.price 350;
    Weapon.SlotPriority 350;
  }
  States
  {
    Spawn:
      AZEW A -1;
      Stop;
  }
}

class BadGun : BaseDeployer
{
  Default
  {
    Tag "Bad";
    Weapon.AmmoType2 "BadAmmo";
    Inventory.PickupMessage "Got Bad!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      BAD1 A -1;
      Stop;
  }
}

class EyePoisonGun : BaseDeployer
{
  Default
  {
    Tag "Poisonous Eye";
    Weapon.AmmoType2 "EyePoisonAmmo";
    Inventory.PickupMessage "Got Poisonous Eye!";
    BaseDeployer.price 4;
    Weapon.SlotPriority 4;
  }
  States
  {
    Spawn:
      ESYM A -1;
      Stop;
  }
}

class EyeExGun : EyePoisonGun
{
  Default
  {
    Tag "Explosive Eye";
    Weapon.AmmoType2 "EyeExAmmo";
    Inventory.PickupMessage "Got Explosive Eye!";
  }
  States
  {
    Spawn:
      ESYZ W -1;
      Stop;
  }
}

class EyeSpiderGun : EyePoisonGun
{
  Default
  {
    Tag "Spider Eye";
    Weapon.AmmoType2 "EyeSpiderAmmo";
    Inventory.PickupMessage "Got Spider Eye!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      ESYZ Y -1;
      Stop;
  }
}

class EyeBatGun : EyePoisonGun
{
  Default
  {
    Tag "Bat Eye";
    Weapon.AmmoType2 "EyeBatAmmo";
    Inventory.PickupMessage "Got Bat Eye!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      ESYZ Z -1;
      Stop;
  }
}

class BeamRevenantGun : BaseDeployer
{
  Default
  {
    Tag "Beam Revenant";
    Weapon.AmmoType2 "BeamRevenantAmmo";
    Inventory.PickupMessage "Got Beam Revenant!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      RASK A -1;
      Stop;
  }
}

class BeamZombieGun : BaseDeployer
{
  Default
  {
    Tag "Beam Zombie";
    Weapon.AmmoType2 "BeamZombieAmmo";
    Inventory.PickupMessage "Got Beam Zombie!";
    BaseDeployer.price 15;
    Weapon.SlotPriority 15;
  }
  States
  {
    Spawn:
      ZBAM A -1;
      Stop;
  }
}

class BFGCommandoGun : BaseDeployer
{
  Default
  {
    Tag "BFG Commando";
    Weapon.AmmoType2 "BFGCommandoAmmo";
    Inventory.PickupMessage "Got BFG Commando!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      BFGZ A -1;
      Stop;
  }
}

class BlindPinkyGun : BaseDeployer
{
  Default
  {
    Tag "Blind Pinky";
    Weapon.AmmoType2 "BlindPinkyAmmo";
    Inventory.PickupMessage "Got Blind Pinky!";
    BaseDeployer.price 3;
    Weapon.SlotPriority 3;
  }
  States
  {
    Spawn:
      BPWA A -1;
      Stop;
  }
}

class BloodDemonGun : BaseDeployer
{
  Default
  {
    Tag "Blood Demon";
    Weapon.AmmoType2 "BloodDemonAmmo";
    Inventory.PickupMessage "Got Blood Demon!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      SRG2 A -1;
      Stop;
  }
}

class BloodFiendGun : BaseDeployer
{
  Default
  {
    Tag "Blood Fiend";
    Weapon.AmmoType2 "BloodFiendAmmo";
    Inventory.PickupMessage "Got Blood Fiend!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      SAR2 A -1;
      Stop;
  }
}

class LurkerGun : BloodFiendGun
{
  Default
  {
    Tag "Lurker";
    Weapon.AmmoType2 "LurkerAmmo";
    Inventory.PickupMessage "Got Lurker!";
    RenderStyle "Translucent";
  }
}

class BloodGhostGun : BaseDeployer
{
  Default
  {
    Tag "Blood Ghost";
    Weapon.AmmoType2 "BloodGhostAmmo";
    Inventory.PickupMessage "Got Blood Ghost!";
    BaseDeployer.price 30;
    Weapon.SlotPriority 30;
  }
  States
  {
    Spawn:
      GHST A -1;
      Stop;
  }
}

class BloodSkullGun : BaseDeployer
{
  Default
  {
    Tag "Blood Skull";
    Weapon.AmmoType2 "BloodSkullAmmo";
    Inventory.PickupMessage "Got Blood Skull!";
    BaseDeployer.price 20;
    Weapon.SlotPriority 20;
  }
  States
  {
    Spawn:
      SWBS A -1;
      Stop;
  }
}

class BlotGun : BaseDeployer
{
  Default
  {
    Tag "Blot";
    Weapon.AmmoType2 "BlotAmmo";
    Inventory.PickupMessage "Got Blot!";
    BaseDeployer.price 1;
    Weapon.SlotPriority 1;
    Inventory.Icon "BLOPA0";
  }
  States
  {
    Spawn:
      BLOP A -1;
      Stop;
  }
}

class BruiserDemonGun : BaseDeployer
{
  Default
  {
    Tag "Bruiser Demon";
    Weapon.AmmoType2 "BruiserDemonAmmo";
    Inventory.PickupMessage "Got Bruiser Demon!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      BRUS A -1;
      Stop;
  }
}

class CacoLichGun : BaseDeployer
{
  Default
  {
    Tag "CacoLich";
    Weapon.AmmoType2 "CacoLichAmmo";
    Inventory.PickupMessage "Got CacoLich!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      CALI A -1;
      Stop;
  }
}

class BerserkCacoLichGun : CacoLichGun
{
  Default
  {
    Tag "Berserk CacoLich";
    Weapon.AmmoType2 "BerserkCacoLichAmmo";
    Inventory.PickupMessage "Got Berserk CacoLich!";
  }
}

class CacolanternGun : BaseDeployer
{
  Default
  {
    Tag "Cacolantern";
    Weapon.AmmoType2 "CacolanternAmmo";
    Inventory.PickupMessage "Got Cacolantern!";
    BaseDeployer.price 65;
    Weapon.SlotPriority 65;
  }
  States
  {
    Spawn:
      HED2 A -1;
      Stop;
  }
}

class CatharsiGun : BaseDeployer
{
  Default
  {
    Tag "Catharsi";
    Weapon.AmmoType2 "CatharsiAmmo";
    Inventory.PickupMessage "Got Catharsi!";
    BaseDeployer.price 15;
    Weapon.SlotPriority 15;
  }
  States
  {
    Spawn:
      SDDM A -1;
      Stop;
  }
}

class ChaingunDemonGun : BaseDeployer
{
  Default
  {
    Tag "Chaingun Demon";
    Weapon.AmmoType2 "ChaingunDemonAmmo";
    Inventory.PickupMessage "Got Chaingun Demon!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      CRG2 A -1;
      Stop;
  }
}

class ChaingunMajorGun : BaseDeployer
{
  Default
  {
    Tag "Chaingun Major";
    Weapon.AmmoType2 "ChaingunMajorAmmo";
    Inventory.PickupMessage "Got Chaingun Major!";
    BaseDeployer.price 40;
    Weapon.SlotPriority 40;
  }
  States
  {
    Spawn:
      CPS2 A -1;
      Stop;
  }
}

class ChaingunSpiderGun : BaseDeployer
{
  Default
  {
    Tag "Chaingun Spider";
    Weapon.AmmoType2 "ChaingunSpiderAmmo";
    Inventory.PickupMessage "Got Chaingun Spider!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      CSPI A -1;
      Stop;
  }
}

class ChubbsGun : BaseDeployer
{
  Default
  {
    Tag "Chubbs";
    Weapon.AmmoType2 "ChubbsAmmo";
    Inventory.PickupMessage "Got Chubbs!";
    BaseDeployer.price 15;
    Weapon.SlotPriority 15;
  }
  States
  {
    Spawn:
      CHBB A -1;
      Stop;
  }
}

class ChainsawZombieGun : BaseDeployer
{
  Default
  {
    Tag "Chainsaw Zombie";
    Weapon.AmmoType2 "ChainsawZombieAmmo";
    Inventory.PickupMessage "Got Chainsaw Zombie!";
    BaseDeployer.price 2;
    Weapon.SlotPriority 2;
  }
  States
  {
    Spawn:
      CHAN A -1;
      Stop;
  }
}

class FloorTentacleGun : BaseDeployer
{
  Default
  {
    Tag "Floor Tentacle";
    Weapon.AmmoType2 "FloorTentacleAmmo";
    Inventory.PickupMessage "Got Floor Tentacle!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      TEN1 A -1;
      Stop;
  }
}

class CeilingTentacleGun : FloorTentacleGun
{
  Default
  {
    Tag "Ceiling Tentacle";
    Weapon.AmmoType2 "CeilingTentacleAmmo";
    Inventory.PickupMessage "Got Ceiling Tentacle!";
    Inventory.Icon "TEN3A0";
  }
  States
  {
    Spawn:
      TEN3 A -1;
      Stop;
  }
}

class CrackodemonGun : BaseDeployer
{
  Default
  {
    Tag "Crackodemon";
    Weapon.AmmoType2 "CrackodemonAmmo";
    Inventory.PickupMessage "Got Crackodemon!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      HED9 A -1;
      Stop;
  }
}

class CrashGun : BaseDeployer
{
  Default
  {
    Tag "Crash";
    Weapon.AmmoType2 "CrashAmmo";
    Inventory.PickupMessage "Got Crash!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      CRSH A -1;
      Stop;
  }
}

class CyberbaronGun : BaseDeployer
{
  Default
  {
    Tag "Cyberbaron";
    Weapon.AmmoType2 "CyberbaronAmmo";
    Inventory.PickupMessage "Got Cyberbaron!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      CBOS A -1;
      Stop;
  }
}

class CyberimpGun : BaseDeployer
{
  Default
  {
    Tag "Cyberimp";
    Weapon.AmmoType2 "CyberimpAmmo";
    Inventory.PickupMessage "Got Cyberimp!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
  }
  States
  {
    Spawn:
      CIMP A -1;
      Stop;
  }
}

class CyberMastermindGun : BaseDeployer
{
  Default
  {
    Tag "Cyber Mastermind";
    Weapon.AmmoType2 "CyberMastermindAmmo";
    Inventory.PickupMessage "Got Cyber Mastermind!";
    BaseDeployer.price 700;
    Weapon.SlotPriority 700;
    Scale 0.15;
  }
  States
  {
    Spawn:
      CYMM A -1;
      Stop;
  }
}

class CyberFiendGun : BaseDeployer
{
  Default
  {
    Tag "Cyber Fiend";
    Weapon.AmmoType2 "CyberFiendAmmo";
    Inventory.PickupMessage "Got Cyber Fiend!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
  }
  States
  {
    Spawn:
      CYFN A -1;
      Stop;
  }
}

class CybruiserGun : BaseDeployer
{
  Default
  {
    Tag "Cybruiser";
    Weapon.AmmoType2 "CybruiserAmmo";
    Inventory.PickupMessage "Got Cybruiser!";
    BaseDeployer.price 300;
    Weapon.SlotPriority 300;
  }
  States
  {
    Spawn:
      CBRU A -1;
      Stop;
  }
}

class DarkCardinalGun : BaseDeployer
{
  Default
  {
    Tag "Dark Cardinal";
    Weapon.AmmoType2 "DarkCardinalAmmo";
    Inventory.PickupMessage "Got Dark Cardinal!";
    BaseDeployer.price 750;
    Weapon.SlotPriority 750;
    Scale 0.28;
    Inventory.Icon "ZARDA0";
  }
  States
  {
    Spawn:
      ZARD A -1;
      Stop;
  }
}

class DarkDevilGun : BaseDeployer
{
  Default
  {
    Tag "Dark Devil";
    Weapon.AmmoType2 "DarkDevilAmmo";
    Inventory.PickupMessage "Got Dark Devil!";
    BaseDeployer.price 15;
    Weapon.SlotPriority 15;
  }
  States
  {
    Spawn:
      DDVL A -1;
      Stop;
  }
}

class DarkImpNamiGun : BaseDeployer
{
  Default
  {
    Tag "Dark Imp Nami";
    Weapon.AmmoType2 "DarkImpNamiAmmo";
    Inventory.PickupMessage "Got Dark Imp Nami!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      DRKI A -1;
      Stop;
  }
}

class DarkImpNetherGun : BaseDeployer
{
  Default
  {
    Tag "Dark Imp Nether";
    Weapon.AmmoType2 "DarkImpNetherAmmo";
    Inventory.PickupMessage "Got Dark Imp Nether!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      DRKF A -1;
      Stop;
  }
}

class DarkImpSTGun : BaseDeployer
{
  Default
  {
    Tag "Dark Imp ST";
    Weapon.AmmoType2 "DarkImpSTAmmo";
    Inventory.PickupMessage "Got Dark Imp ST!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      DRKS A -1;
      Stop;
  }
}

class DarkImpVoidGun : BaseDeployer
{
  Default
  {
    Tag "Dark Imp Void";
    Weapon.AmmoType2 "DarkImpVoidAmmo";
    Inventory.PickupMessage "Got Dark Imp Void!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      DRKV A -1;
      Stop;
  }
}

class DefilerGun : BaseDeployer
{
  Default
  {
    Tag "Defiler";
    Weapon.AmmoType2 "DefilerAmmo";
    Inventory.PickupMessage "Got Defiler!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
  }
  States
  {
    Spawn:
      DEFI A -1;
      Stop;
  }
}

class DeathIncarnateGun : BaseDeployer
{
  Default
  {
    Tag "Death Incarnate";
    Weapon.AmmoType2 "DeathIncarnateAmmo";
    Inventory.PickupMessage "Got Death Incarnate!";
    BaseDeployer.price 30;
    Weapon.SlotPriority 30;
  }
  States
  {
    Spawn:
      INCA A -1;
      Stop;
  }
}

class DeepOneGun : BaseDeployer
{
  Default
  {
    Tag "Deep One";
    Weapon.AmmoType2 "DeepOneAmmo";
    Inventory.PickupMessage "Got Deep One!";
    BaseDeployer.price 300;
    Weapon.SlotPriority 300;
  }
  States
  {
    Spawn:
      CUTH A -1;
      Stop;
  }
}

class DemolisherGun : BaseDeployer
{
  Default
  {
    Tag "Demolisher";
    Weapon.AmmoType2 "DemolisherAmmo";
    Inventory.PickupMessage "Got Demolisher!";
    BaseDeployer.price 750;
    Weapon.SlotPriority 750;
    Scale 0.15;
  }
  States
  {
    Spawn:
      DEMO A -1;
      Stop;
  }
}

class DevastatorZombieGun : BaseDeployer
{
  Default
  {
    Tag "Devastator Zombie";
    Weapon.AmmoType2 "DevastatorZombieAmmo";
    Inventory.PickupMessage "Got Devastator Zombie!";
    BaseDeployer.price 75;
    Weapon.SlotPriority 75;
  }
  States
  {
    Spawn:
      DEVZ A -1;
      Stop;
  }
}

class DevilGun : BaseDeployer
{
  Default
  {
    Tag "Devil";
    Weapon.AmmoType2 "DevilAmmo";
    Inventory.PickupMessage "Got Devil!";
    BaseDeployer.price 10;
    Weapon.SlotPriority 10;
  }
  States
  {
    Spawn:
      TRO2 A -1;
      Stop;
  }
}

class DiabloistGun : BaseDeployer
{
  Default
  {
    Tag "Diabloist";
    Weapon.AmmoType2 "DiabloistAmmo";
    Inventory.PickupMessage "Got Diabloist!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      DIAB A -1;
      Stop;
  }
}

class DivineShadowGun : BaseDeployer
{
  Default
  {
    Tag "Divine Shadow";
    Weapon.AmmoType2 "DivineShadowAmmo";
    Inventory.PickupMessage "Got Divine Shadow!";
    BaseDeployer.price 300;
    Weapon.SlotPriority 300;
  }
  States
  {
    Spawn:
      VIL1 A -1;
      Stop;
  }
}

class DoomRPGGhoulGun : BaseDeployer
{
  Default
  {
    Tag "Ghoul";
    Weapon.AmmoType2 "DoomRPGGhoulAmmo";
    Inventory.PickupMessage "Got Ghoul!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      GHUL A -1;
      Stop;
  }
}

class DoubleChaingunnerGun : BaseDeployer
{
  Default
  {
    Tag "Double Chaingunner";
    Weapon.AmmoType2 "DoubleChaingunnerAmmo";
    Inventory.PickupMessage "Got Double Chaingunner!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
  }
  States
  {
    Spawn:
      DPOS A -1;
      Stop;
  }
}

class DuneWarriorGun : BaseDeployer
{
  Default
  {
    Tag "Dune Warrior";
    Weapon.AmmoType2 "DuneWarriorAmmo";
    Inventory.PickupMessage "Got Dune Warrior!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
  }
  States
  {
    Spawn:
      ZHRT A -1;
      Stop;
  }
}

class EnhancedCacodemonGun : BaseDeployer
{
  Default
  {
    Tag "Enhanced Cacodemon";
    Weapon.AmmoType2 "EnhancedCacodemonAmmo";
    Inventory.PickupMessage "Got Enhanced Cacodemon!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      ENCD A -1;
      Stop;
  }
}

class EtherealSoulGun : BaseDeployer
{
  Default
  {
    Tag "Ethereal Soul";
    Weapon.AmmoType2 "EtherealSoulAmmo";
    Inventory.PickupMessage "Got Ethereal Soul!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
  }
  States
  {
    Spawn:
      ETHS A -1;
      Stop;
  }
}

class ExterminatorGun : BaseDeployer
{
  Default
  {
    Tag "Exterminator";
    Weapon.AmmoType2 "ExterminatorAmmo";
    Inventory.PickupMessage "Got Exterminator!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
  }
  States
  {
    Spawn:
      EXTR A -1;
      Stop;
  }
}

class FallenGun : BaseDeployer
{
  Default
  {
    Tag "Fallen";
    Weapon.AmmoType2 "FallenAmmo";
    Inventory.PickupMessage "Got Fallen!";
    BaseDeployer.price 25;
    Weapon.SlotPriority 25;
    Scale 0.2;
  }
  States
  {
    Spawn:
      FALN A -1;
      Stop;
  }
}

class FemaleScientistGun : BaseDeployer
{
  Default
  {
    Tag "Female Scientist";
    Weapon.AmmoType2 "FemaleScientistAmmo";
    Inventory.PickupMessage "Got Female Scientist!";
    BaseDeployer.price 0;
    Weapon.SlotPriority 0;
  }
  States
  {
    Spawn:
      FSZK A -1;
      Stop;
  }
}

class FemalePlasmaGun : BaseDeployer
{
  Default
  {
    Tag "Female Plasma Gunner";
    Weapon.AmmoType2 "FemalePlasmaAmmo";
    Inventory.PickupMessage "Got Female Plasma Gunner!";
    BaseDeployer.price 5;
    Weapon.SlotPriority 5;
  }
  States
  {
    Spawn:
      PZOW A -1;
      Stop;
  }
}

class FemaleRailGun : BaseDeployer
{
  Default
  {
    Tag "Female Railgunner";
    Weapon.AmmoType2 "FemaleRailAmmo";
    Inventory.PickupMessage "Got Female Railgunner!";
    BaseDeployer.price 5;
    Weapon.SlotPriority 5;
  }
  States
  {
    Spawn:
      RZOW A -1;
      Stop;
  }
}

class FemaleSergeantGun : BaseDeployer
{
  Default
  {
    Tag "Female Sergeant";
    Weapon.AmmoType2 "FemaleSergeantAmmo";
    Inventory.PickupMessage "Got Female Sergeant!";
    BaseDeployer.price 5;
    Weapon.SlotPriority 5;
  }
  States
  {
    Spawn:
      CZOW A -1;
      Stop;
  }
}

class FemaleZombieGun : BaseDeployer
{
  Default
  {
    Tag "Female Zombie";
    Weapon.AmmoType2 "FemaleZombieAmmo";
    Inventory.PickupMessage "Got Female Zombie!";
    BaseDeployer.price 1;
    Weapon.SlotPriority 1;
  }
  States
  {
    Spawn:
      ZOMW A -1;
      Stop;
  }
}

class FlamerZombieGun : BaseDeployer
{
  Default
  {
    Tag "Flamer Zombie";
    Weapon.AmmoType2 "FlamerZombieAmmo";
    Inventory.PickupMessage "Got Flamer Zombie!";
    BaseDeployer.price 35;
    Weapon.SlotPriority 35;
  }
  States
  {
    Spawn:
      FLMZ A -1;
      Stop;
  }
}

class FleshSpawnGun : BaseDeployer
{
  Default
  {
    Tag "Fleshspawn";
    Weapon.AmmoType2 "FleshSpawnAmmo";
    Inventory.PickupMessage "Got Fleshspawn!";
    BaseDeployer.price 5;
    Weapon.SlotPriority 5;
    Scale 0.25;
  }
  States
  {
    Spawn:
      FLSP A -1;
      Stop;
  }
}

class FleshWizardGun : BaseDeployer
{
  Default
  {
    Tag "Flesh Wizard";
    Weapon.AmmoType2 "FleshWizardAmmo";
    Inventory.PickupMessage "Got Flesh Wizard!";
    BaseDeployer.price 1;
    Weapon.SlotPriority 1;
  }
  States
  {
    Spawn:
      LMWZ A -1;
      Stop;
  }
}

class XWizardGun : BaseDeployer
{
  Default
  {
    Tag "X Wizard";
    Weapon.AmmoType2 "XWizardAmmo";
    Inventory.PickupMessage "Got X Wizard!";
    BaseDeployer.price 2;
    Weapon.SlotPriority 2;
  }
  States
  {
    Spawn:
      LMWZ A -1;
      Stop;
  }
}

class HadesElementalGun : BaseDeployer
{
  Default
  {
    Tag "Hades Elemental";
    Weapon.AmmoType2 "HadesElementalAmmo";
    Inventory.PickupMessage "Got Hades Elemental!";
    BaseDeployer.price 350;
    Weapon.SlotPriority 350;
  }
  States
  {
    Spawn:
      HELE A -1;
      Stop;
  }
}

class HaedexebusGun : BaseDeployer
{
  Default
  {
    Tag "Haedexebus";
    Weapon.AmmoType2 "HaedexebusAmmo";
    Inventory.PickupMessage "Got Haedexebus!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
    Scale 0.25;
  }
  States
  {
    Spawn:
      UNMB A -1;
      Stop;
  }
}

class HectebusGun : BaseDeployer
{
  Default
  {
    Tag "Hectebus";
    Weapon.AmmoType2 "HectebusAmmo";
    Inventory.PickupMessage "Got Hectebus!";
    BaseDeployer.price 150;
    Weapon.SlotPriority 150;
  }
  States
  {
    Spawn:
      HECT A -1;
      Stop;
  }
}

class HellPaladinGun : BaseDeployer
{
  Default
  {
    Tag "Hell Paladin";
    Weapon.AmmoType2 "HellPaladinAmmo";
    Inventory.PickupMessage "Got Hell Paladin!";
    BaseDeployer.price 125;
    Weapon.SlotPriority 125;
  }
  States
  {
    Spawn:
      HPAL A -1;
      Stop;
  }
}

class HellWarriorGun : BaseDeployer
{
  Default
  {
    Tag "Hell Warrior";
    Weapon.AmmoType2 "HellWarriorAmmo";
    Inventory.PickupMessage "Got Hell Warrior!";
    BaseDeployer.price 50;
    Weapon.SlotPriority 50;
  }
  States
  {
    Spawn:
      HWAR A -1;
      Stop;
  }
}

class HellsFuryGun : BaseDeployer
{
  Default
  {
    Tag "Hell's Fury";
    Weapon.AmmoType2 "HellsFuryAmmo";
    Inventory.PickupMessage "Got Hell's Fury!";
    BaseDeployer.price 125;
    Weapon.SlotPriority 125;
  }
  States
  {
    Spawn:
      HFRY A -1;
      Stop;
  }
}

class HellstormArchonGun : BaseDeployer
{
  Default
  {
    Tag "Hellstorm Archon";
    Weapon.AmmoType2 "HellstormArchonAmmo";
    Inventory.PickupMessage "Got Hellstorm Archon!";
    BaseDeployer.price 300;
    Weapon.SlotPriority 300;
  }
  States
  {
    Spawn:
      BOS3 A -1;
      Stop;
  }
}

class LordOfHeresyGun : BaseDeployer
{
  Default
  {
    Tag "Lord Of Heresy";
    Weapon.AmmoType2 "LordOfHeresyAmmo";
    Inventory.PickupMessage "Got Lord Of Heresy!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      LOHS A -1;
      Stop;
  }
}

class OverlordGun : BaseDeployer
{
  Default
  {
    Tag "Overlord";
    Weapon.AmmoType2 "OverlordAmmo";
    Inventory.PickupMessage "Got Overlord!";
    BaseDeployer.price 500;
    Weapon.SlotPriority 500;
    Scale 0.2;
  }
  States
  {
    Spawn:
      OVER A -1;
      Stop;
  }
}

class PhantomGun : BaseDeployer
{
  Default
  {
    Tag "Phantom";
    Weapon.AmmoType2 "PhantomAmmo";
    Inventory.PickupMessage "Got Phantom!";
    BaseDeployer.price 200;
    Weapon.SlotPriority 200;
  }
  States
  {
    Spawn:
      PHAN A -1;
      Stop;
  }
}
/* copy pastable example
class AbaddonGun : BaseDeployer
{
  Default
  {
    Tag "Abaddon";
    Weapon.AmmoType2 "AbaddonAmmo";
    Inventory.PickupMessage "Got Abaddon!";
    BaseDeployer.price 100;
    Weapon.SlotPriority 100;
    Scale 0.4;
  }
  States
  {
    Spawn:
      HED3 A -1;
      Stop;
  }
}
*/