class CompanionWalkToCorpse : EventHandler
{
  override void WorldThingDied(WorldEvent e){
    if(e.Thing && e.Thing.bIsMonster && !e.Thing.bFriendly) {

      // makes companions walk over to last killed enemy corpse (if theres no threats around)
      if(e.Thing.bIsMonster && !e.Thing.bFriendly && e.Thing.target && e.Thing.target.GetSpecies() == "Companion"){
        Actor pp = Actor.Spawn("PatrolPoint", e.Thing.pos);
        e.Thing.target.goal = pp;
      }
    }
  }
}