// --------------------------------------------------------------------------
//
// Fist 
//
// --------------------------------------------------------------------------

class MyFist : Fist replaces Fist
{
	Default
	{
    +WEAPON.NOALERT
	}
	States
	{
		AltFire:
			PUNG B 4;
			PUNG C 4
			{
				A_StartSound("Weapons/BioFire");
				A_FireProjectile("BioProjAlt");
			}
			PUNG D 5;
			PUNG C 4;
			PUNG B 5 A_ReFire;
			Goto Ready;
	}
}