class Utilities
{
  static int angleToMoveDir(double angle){
    int moveDir = Actor.Normalize180(angle);
    if (moveDir < 0){
      moveDir += 360;
    }
    return ((moveDir+22.5) / 45) % 8;
  }

  static bool canAfford(int balance, int price){
    if (balance >= price){
      return true;
    }else{
      console.printf("Price:"..price.." Balance:"..balance);
      console.printf("Not Enough Money");
    }
    return false;
  }
}