Class FemalePlasma : Actor
{
  Default
  {
    MONSTER;
    +FRIENDLY
    Species "Companion";
    DamageFactor "Companion", 0;
    Health 40;
    Radius 20;
    Height 56;
    Speed 10;
    PainChance 200;
    +FLOORCLIP
    seesound "fem/sight";
    painsound "fem/pain";
    deathsound "fem/death";
    activesound "fem/active";
    Obituary "%o got burned by a plasma female zombie!";
    DropItem "Cell";
  }
  States
  {
    Spawn:
      PZOW AB 10 A_Look;
      Loop;
    See:
      PZOW AABBCCDD 4 A_Chase;
      Loop;
    Missile:
      TNT1 A 0 A_AlertMonsters(0, AMF_TARGETEMITTER);
      PZOW E 10 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      PZOW E 5 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      PZOW E 5 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      PZOW E 5 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      PZOW E 5 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      PZOW E 5 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      PZOW E 5 A_FaceTarget;
      PZOW F 5 A_SpawnProjectile("CompanionPlasmaBall");
      Goto See;
    Pain:
      PZOW G 3;
      PZOW G 3 A_Pain;
      Goto See;
    Death:
      PZOW H 5;
      PZOW I 5 A_Scream;
      PZOW J 5 A_Fall;
      PZOW K 5;
      PZOW L 5;
      PZOW M 5;
      PZOW N -1;
      Stop;
    XDeath:
      PZOW O 5;
      PZOW P 5 A_XScream;
      PZOW Q 5 A_Fall;
      PZOW RSTUV 5;
      PZOW W -1;
      Stop;
    Raise:
      PZOW MLKJIH 5;
      Goto See;
  }
}
