

class HeatSeekingMissile : Actor
{
  Default
  {
    +SEEKERMISSILE
    +RANDOMIZE
    +DEHEXPLOSION
    +ROCKETTRAIL
    +SCREENSEEKER
    Radius 11;
    Height 8;
    Speed 25;
    Damage 50;
    PROJECTILE;
    Species "Companion";
    DamageType "Companion";
    SeeSound "Ally/Seeker";
    DeathSound "Seeker/Explode";
    Decal "Scorch";
  }
  States
  {
    Spawn:
      HRKT A 1 bright A_SeekerMissile(9,6,SMF_LOOK|SMF_CURSPEED,50,10);
      HRKT A 0 A_SpawnItemEx ("MissileTrail", 3, 0, 0, 1);
      loop;
    Death:
      FX08 A 6 bright A_Explode(96,128);
      FX08 BCDEFGH 4 bright;
      Stop;
  }
}

class MissileTrail : Actor
{
  Default
  {
    +NoClip
    PROJECTILE;
    RenderStyle "Add";
    Alpha 0.4;
  }
  States
  {
    Spawn:
      FX04 ABCDE 1 Bright;
      Stop;
  }
}

class CompanionGrenade : Actor
{
  Default
  {
    -NOGRAVITY
    +LOWGRAVITY
    +ROCKETTRAIL
    Radius 11;
    Height 8;
    Speed 25;
    Damage 30;
    BounceType "Hexen";
    SeeSound "Ally/GrenadeBounce";
    DeathSound "Ally/GrenadeBang";
    PROJECTILE;
    Species "Companion";
    DamageType "Companion";
  }
  States
  {
    Spawn:
      MGRN A 0;
      MGRN A 4;
      MGRN A 24;
      goto Death;
    Death:
      MISL B 8 bright A_Explode(128,96,XF_EXPLICITDAMAGETYPE,false,0,0,10,"CompanionBulletPuff","Companion");
      MISL C 6 bright;
      MISL D 4 bright;
      Stop;
  }
}

class CompanionBFG10kShot : Actor
{
  Default
  {
    +NOBLOCKMAP
    +NOGRAVITY
    +ACTIVATEIMPACT
    +ACTIVATEPCROSS
    +NOTELEPORT
    +PUFFONACTORS
    +PUFFGETSOWNER
    +FORCERADIUSDMG
    Radius 14;
    Height 8;
    Speed 25;
    Damage 320;
    Species "Companion";
    DamageType "Companion";
    RenderStyle "Add";
    Alpha 0.75;
    SeeSound "marine/bfg10kx";
    AttackSound "marine/bfg10kx";
    DeathSound "BFG10kMarine/ShotEnd";
  }
  States
  {
    Spawn:
      BFE1 A 0 Bright;
      BFE1 A 3 Bright A_Detonate;
      BFE1 BCDEF 3 Bright;
      Stop;
  }
}

class CompanionFire : Actor
{
  Default
  {
    +THRUGHOST
    +FORCERADIUSDMG
    Radius 2;
    Height 4;
    Speed 19;
    Damage 5;
    PROJECTILE;
    DontHurtShooter;
    RenderStyle "ADD";
    Alpha 0.67;
    SeeSound "Marine/Flamer";
    DeathSound "Marine/Scorch";
    Species "Companion";
    DamageType "Companion";
  }
  States
  {
    Spawn:
      TNT1 A 2 Bright;
      FRFX ABCD 2 Bright A_Explode(3,8);
      FRFX D 0 Bright A_Lowgravity;
      FRFX EFG 2 Bright A_Explode(3,16);
      FRFX HIJ 2 Bright A_Explode(3,32);
      FRFX KLM 2 Bright A_Explode(3,64);
      FRFX NO 2 Bright;
      Stop;
    Death:
      FRFX HIJ 2 Bright A_Explode(3,32);
      FRFX J 0 A_SpawnProjectile("CompanionDropFire");
      FRFX KLM 2 Bright A_Explode(3,64);
      FRFX NO 2 Bright;
      Stop;
  }
}

class CompanionDropFire : Actor
{
  Default
  {
    -NOGRAVITY
    +LOWGRAVITY
    +NOEXPLODEFLOOR
    +NODAMAGETHRUST
    Radius 8;
    Height 40;
    PROJECTILE;
    DontHurtShooter;
    RenderStyle "ADD";
    Alpha 0.90;
    Species "Companion";
    DamageType "Companion";
  }
  States
  {
    Spawn:
      FLME A 1 Bright A_StartSound("Marine/onfire");
      FLME A 1 Bright A_Explode(1,16);
      FLME BCDEFGHIJKLMN 2 Bright A_Explode(1,16);
      FLME A 1 Bright A_StartSound("Marine/onfire");
      FLME A 1 Bright A_Explode(1,32);
      FLME BCDEFGHIJKLMN 2 Bright A_Explode(1,16);
      FLME A 1 Bright A_StartSound("Marine/onfire");
      FLME A 1 Bright A_Explode(1,32);
      FLME BCDEFGHIJKLMN 2 Bright A_Explode(1,16);
      FLME A 1 Bright A_StartSound("Marine/onfire");
      FLME A 1 Bright A_Explode(1,32);
      FLME BCDEFGHIJKLMN 2 Bright A_Explode(1,16);
      FLME A 1 Bright A_StartSound("Marine/onfire");
      FLME A 1 Bright A_Explode(1,32);
      FLME BCDEFGHIJKLMN 2 Bright A_Explode(1,16);
      FLME A 0 A_Jump(192,1);
      loop;
      TNT1 A 0;
      goto death;
    Death:
      TNT1 A 1 Bright;
      Stop;
  }
}